// <auto-generated />
namespace Reuse2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class usuarioInstituicao2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usuarioInstituicao2));
        
        string IMigrationMetadata.Id
        {
            get { return "201605051322134_usuarioInstituicao2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
